### ISSUE TITLE
Inaturalist tab provides inappropriate taxa

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#100]
https://orthoptera.speciesfile.org/otus/807354/inaturalist

**Comment by LocoDelAssembly** [comment]
Just sharing small experiment, not sure if it is actually a good idea but using https://api.inaturalist.org/v1/observations?taxon_name=Otumba&per_page=60 (`taxon_name` instead of `q`) yields far less results (but misidentifications are still possible).

Otumba happens to be a locality in Mexico as well, so I guess that is what is being matched too.

> taxon_name
    Filter by iNat taxon name. Note that this will also select observations of descendant taxa. **Note that names are not unique, so if the name matches multiple taxa, no observations may be returned.**
    Allowed values: Name string 

_(Notice bold text before considering just changing to this param)_

cc @jlpereira @mjy

**Comment by klausriede** [comment]
Yes, of course the query has to be limited to taxonname! I wonder if it might be better to query gbif, which would give us Xenocanto + inaturalist. You might think of 3 tabs: more points via gbif (limited to georeferenced data), more pics via gbif (limited to media content= img, but not restricted to georeferenced), more sounds via gbif (limiting media content to sound and video).
