### ISSUE TITLE
Isopsera brachystylata is still listed

### ISSUE THREAD

**Issue by SeanCozart** [sfg-taxonpages/orthoptera#107]
It appears that the species named Isopsera brachystylata was transferred to a new genus, but both taxa are still in the database. 

https://orthoptera.speciesfile.org/otus/846879/overview -- old genus
https://orthoptera.speciesfile.org/otus/846411/overview -- new genus

**Comment by MMCigliano** [comment]
Issue solved. 
Thank you very much @SeanCozart

**Comment by klausriede** [comment]
I suppose both names are still in the database, but one as [c] ?

**Comment by MMCigliano** [comment]
@klausriede  There was an error in the original database with the first author name. 
As Liu, Chunxiang, in the reference for the combination name Qinlingea brachystylata (Liu & Wang, 1998), http://orthoptera.archive.speciesfile.org/Common/basic/Taxa.aspx?TaxonNameID=1136499

As Liu, X.-W. in the reference for the protonym Isopsera brachystylata Liu & Wang, 1998
http://orthoptera.archive.speciesfile.org/Common/basic/Taxa.aspx?TaxonNameID=1218853

**Comment by klausriede** [comment]
maybe it would be helpful to include the combinations in the lists, as is already done with synonyms. Generating a list of Isopsera species would then include the old combination I brachystylata, but without a link, and a linked Q brachystylata below, so it is evident what happened. Otherwise it is often difficult to find even well-known species

**Comment by MMCigliano** [comment]
@klausriede, currently  you can read the history of the name Qinlingea brachystylata (Liu & Wang, 1998) in the Nomenclature panel
