### ISSUE TITLE
Paeroecanthus podagrosus

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#108]
How can we differentiate a taxonomical nomenclature reference from a nontaxonomic reference? https://orthoptera.speciesfile.org/otus/836353/overview Our Schmidt Riede references are later, but not taxonomical, and we were unaware of the Gorochov paper. But for the outsider this might look like a nomenclature change

**Comment by typophyllum** [comment]
Good question. There was no distinction in the old OSF and all references with filled-in Nomenclator (scientific name used in corresponding reference) migrated to Browse nomenclature.

Currently we add all new references to Browse nomenclature.

Theoretically all references could be more or less nomenclaturally relevant, like misspellings, incorrect combinations (i.e. wrong gender agreement), rarely used correct combinations, etc.

So "Nomenclature references" is currently misleading and the entire issue a little bit contradictory, since TaxonPages shows data from browse OTU, but not citations added to only the OTU (which we currently don't do).
