### ISSUE TITLE
What happened to Chiriquia gracilis?

### ISSUE THREAD

**Issue by SeanCozart** [sfg-taxonpages/orthoptera#110]
We have this species listed in iNaturalist, and the name was pulled from OSF Version 5.0 in 2018. Now there is no Chiriquia gracilis listed anywhere on the site. Where did it go and is there a way to look back on previous versions of the site?

I tried doing some digging on my end of things, and I did find one source claiming it was described in Bruner 1900, and that paper has two Tetrigidae with the species epithet; Paratettix and Lophoscirtes. It looks like it might be a synonym of Paratettix gracilis based on GBIF.

https://ecdysis.org/taxa/index.php?tid=1030084&taxauthid=1&clid=0
https://www.mindat.org/taxon-9145861.html

**Comment by typophyllum** [comment]
Looking in the Wayback Machine (Internet Archive) on the page of the genus _Chiriquia_ (URL is http://orthoptera.speciesfile.org/Common/basic/Taxa.aspx?TaxonNameID=1100999) there was no _gracilis_ in 2016 (March 19) but in 2020 (July 15):

![imagen](https://github.com/user-attachments/assets/afe21f6a-c705-4fb2-8f52-c90deb8f01c8)

_Nephele gracilis_ is indeed the original combination of _Paratettix gracilis_ (Bruner, 1900).

**Comment by SeanCozart** [comment]
So are we adding Chiriquia gracilis back into the system as a synonym of Paratettix gracilis? Seems kind of strange that at one point, you could look up the name on the site and get a ping, but now you don't.

**Comment by typophyllum** [comment]
The combination "_Chiriquia gracilis_" was a temporary database artifact that has never been published. Sometime in 2020, when _Paratettix gracilis_ (Bruner, 1900) had an incorrect original reference erroneously citing _Tettix gracilis_, _Nephele gracilis_ was "discovered". It was entered under _Chiriquia_ only because _Nephele_ was a synonym under that genus. The error persisted through all of 2022 and was corrected sometime before the migration in 2023.

**Comment by klausriede** [comment]
Fascinating! Infact there was sufficient time for the artefact to escape and populate the inaturalist zooverse
