### ISSUE TITLE
female type specimen photographs missing for https://orthoptera.speciesfile.org/otus/837214/specimen_records

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#117]
cf with femalve views from Ingrisch/Dorsa http://orthoptera.archive.speciesfile.org/Common/basic/ShowAllImages.aspx?SpecimenID=6615

**Comment by typophyllum** [comment]
The corresponding specimen record got lost. The four pictures are with the OTU, in the Overview they appear at the end of the sequence.

**Comment by klausriede** [comment]
@mjy @MMCigliano  as said it would be good to know what else got lost, and reintegrate it into the migrated version. This can easily be done by some simple check routines. It is like comparing packing and unpacking lists when you move!

**Comment by mjy** [comment]
@klausriede 

> This can easily be done by some simple check routines. It is like comparing packing and unpacking lists when you move!

Not really.  These types of migrations are multi-step.  In the first step we code a match to the best of our ability, remember we're not moving box1 from A to B, we're translating box1 from A into boxes(1,2,n) in B, this is fundamentally different than the analogy you lay out. We've long since passed the primary import stage in which we do the best we can to define and execute the "moving van logistics".  Tactically we have entered into what we see as the expert-validation process.  Here experts like yourself start to spot systematic problems, in doing so the begin to better understand how the "boxes" changed from A to B.  They then provide us with examples of the problems that could be fixed, and in they require systematic fixes that we can efficiently run, we run them.

We  depend on you, and the OSF community to help here.  How can you do this? You can get access to the data before and after (for example downloading tables) and process them with your own tools, or the SQL database, or derivative outputs (catalog dumps, CSV download, etc.). Refine is particularly useful, you might pick up some scripting tools and check that way too.  I'd also suggest you explore GlobalNames and think about how to use it's "diff" tools and querying, this may be a powerful way to identify systemic issues.

**Comment by typophyllum** [comment]
I added the _Arachnocephalus vestitus_ specimen. In the old OSF it has an incorrect reference and uncertain locality, now it's geo-referenced.

![imagen](https://github.com/user-attachments/assets/1e977583-ac60-4ac7-a847-5f7573d37e53)
