### ISSUE TITLE
depository Andriana pyramidata do not coincide

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#20]
no further comment...

**Comment by klausriede** [comment]
http://orthoptera.speciesfile.org/Common/specimen/ShowSpecimen.aspx?Router=NewPage 
![grafik](https://github.com/sfg-taxonpages/orthoptera/assets/12816652/2964aa76-b9a0-45d3-8a8e-1cb28c10fea0)
This paratype is shown in TP https://sfg-taxonpages.github.io/orthoptera/#/otus/807147/overview
Should we only see the Holotype repository in TP ? I think we should see all paratypes and their repositories also in TP. particularly if images are shown! Source of images should be complete, incl repository - maybe inside the pic? Occurence points on the map are missing

**Comment by mabecabrera** [comment]
Occurence points are missing because there are no georeferences for any of the specimens in that species in OSF. Only asserted distributions. 
<img width="329" alt="image" src="https://github.com/sfg-taxonpages/orthoptera/assets/63611746/74d242a2-36b1-4230-8218-732a168fa801">


We will continue with the discussion for improvements on the display of the images and their metadata in the Public View in this issue placed in the Taxon Pages Git Hub. 
https://github.com/SpeciesFileGroup/taxonpages/issues/153

We will keep this git hub for migration problems ONLY.
