### ISSUE TITLE
Gryllacridid from Liechtenstein

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#39]
that´s a funny one: https://sfg-taxonpages.github.io/orthoptera/#/otus/840128/overview

**Comment by typophyllum** [comment]
That the name of the author Liechtenstein resulted in a probably incorrect type locality in Liechenstein is an error in the old OSF. 

The Kirby 1910 citation using the protonym didn't migrate, and apparently we'll need to select the source for nomen dubium relationships manually (have to check this in our Spanish github section with things that need to be fixed manually).

This is also a case where the the migration produced a no-author synonym:
![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/36f28612-d76c-4924-bb2e-51e90252de39)
![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/21dd6ff1-aa9d-4d90-9323-35f486a60474)

I fixed the citations and deleted the type since its existence and whereabouts are unknown.

**Comment by klausriede** [comment]
Indeed! Maps make inconsistencies visible....

**Comment by klausriede** [comment]
Here another Lichtenstein species https://sfg-taxonpages.github.io/orthoptera/#/otus/927930/overview - however I do not find the synonymized species M. rosalia....

**Comment by klausriede** [comment]
@typophyllum  there is also a photograph of D. salvifolius from a specimen collected by me, determined by you http://orthoptera.speciesfile.org/Common/basic/ShowImage.aspx?TaxonNameID=1140804&ImageID=157471

**Comment by klausriede** [comment]
it seems the photograph is here https://sfg-taxonpages.github.io/orthoptera/#/otus/803994/overview but you cannot see where it was collected. For TP the collection object number is useless, collection data would be more useful. As it is the user cannot differentiate between the type photographs and the specimens collected by me in Ecuador. Writing the info into the picture might be a solution. MAybe discuss this as a separate issue?

**Comment by typophyllum** [comment]
There is still the problem that the search shows invalid OTUs.

![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/9d0e9d04-7cd6-4255-9a51-8c3a7400aa2f)

The current TP version is only an overview. We need an additional page/tab with the specimens and assorted photos.
