### ISSUE TITLE
more decimal latitudes out of range

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#49]
![grafik](https://github.com/sfg-taxonpages/orthoptera/assets/12816652/6cac9653-0730-445c-a044-939da298d54a)

No idea how this latitude out of range affects map display, but it is definitely wrong. Should be easy to check for latlongs out of range.

Ephippigerini DcW https://orthoptera.speciesfile.org/otus/841663/overview

**Comment by mjy** [comment]
@klausriede thanks for exploring the DwC!!

**Comment by LocoDelAssembly** [comment]
@klausriede what system locale are you using in Windows? Spanish?

Looks good at my end using LibreOffice Calc in Ubuntu:
![image](https://github.com/sfg-taxonpages/orthoptera/assets/4991925/88ef994a-ba4b-4926-8637-461d8a4f9c03)

I think although I have the OS in English language, locale is Spanish (Argentina), but I think Calc ignores and interpretes period as decimal separator rather than thousands separator.

**Comment by LocoDelAssembly** [comment]
Because if following a period there are not exactly 3 digits then it is not assumed to be thousands separator and cell becomes text type (notice alignment is different in your capture for those coordinates that were not messed up).

I believe georeferences are checked both by TW and database system. Don't remember what happens with verbatim lat/log, but DwC is probably validated? @mjy

**Comment by mjy** [comment]
There is a corresponding taxonworks issue IIRC, but yes, when we export values to DwC then we use Georeference values that may not appear the same as the verbatim IIRC.

**Comment by klausriede** [comment]
![grafik](https://github.com/sfg-taxonpages/orthoptera/assets/12816652/0cce736d-b568-459f-9c8b-0b811db9b16b)

ANOTHER outofrange case from nemobiinae csv, using 
![grafik](https://github.com/sfg-taxonpages/orthoptera/assets/12816652/0bf71b25-e28c-4ce9-80f4-cdd01083cd07)

**Comment by klausriede** [comment]
...and bingo, correct in CSV 
![grafik](https://github.com/sfg-taxonpages/orthoptera/assets/12816652/fd5b145f-b29b-4004-b558-592f6239ffa1)
