### ISSUE TITLE
Calliptaminae missing

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#6]
I was searching for Calliptaminae. This should appear in the dropdown list after entering Callipt , see OSF old but it does not
![grafik](https://github.com/sfg-taxonpages/orthoptera/assets/12816652/14eb0175-8046-4d99-a147-004ce7d6c2dd)

**Comment by klausriede** [comment]
sorry solved, it does appear somewhere scrolling down...I strongly suggest to introduce a hierarchy, listing Families first, the genera, then species...

**Comment by klausriede** [comment]
semisolved: in any case this 
![grafik](https://github.com/sfg-taxonpages/orthoptera/assets/12816652/8399c1c2-8d6f-452a-9fd9-f5b549475576)

should not appear when typing Calliptaminae

**Comment by mjy** [comment]
While there is presently an issue with the OTU autocomplete (maybe, not sure if this one is resolved) there is a ton of intelligence behind it, it trys to predict many things, including using some taxonomic intelligence.  Try typing something into a Google autocomplete, I'm sure there are a million results returned that you feel are not what you want, same thing here.  Use a Capital C, should help (but note again there are a couple of things we broke recently that might be impacting what you see).

**Comment by klausriede** [comment]
I strongly suggest to emulate the result for Callipt in old OSF which at least for me as a user makes sense
![grafik](https://github.com/sfg-taxonpages/orthoptera/assets/12816652/57c884ab-2435-45b5-8a8a-e7051a413ddb)

**Comment by mjy** [comment]
Sorry for the abruptness.  Closed because there are known problems, the result you are seeing isn't what you'll see very shortly so it's not really worth spinng our wheels on.  I strongly suspect that the next updates will make this go away, i.e. see the fixes currently in dev (for TW, not TP, but it will be similar) here:

<img width="622" alt="Screenshot 2023-09-13 at 2 47 53 PM" src="https://github.com/sfg-taxonpages/orthoptera/assets/22600/e9c1d3b8-e1b7-4777-acb9-190b8dcc0121">
