### ISSUE TITLE
Heteracris type species and specimen

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#64]
https://orthoptera.speciesfile.org/otus/820707/overview
Heteracris herbacea is the type species of the genus Heteracris. It appears in the Heteracris desc. list as superspecies . The superspecies page does not contain any info (why superspecies, specimen etc) . I think the type species for the genus should be appear in the list of descendants in correct alphabetical order https://orthoptera.speciesfile.org/otus/820638/overview

**Comment by typophyllum** [comment]
_Heteracris herbacea_ is among the descendents of the superspecies _herbacea_ (a species group in the old OSF). The superspecies should perhaps be listed first instead of being integrated in the alphabethical order according to "supersp."

![imagen](https://github.com/sfg-taxonpages/orthoptera/assets/33210201/8006e176-870f-4d49-8f9a-ab5cb2bbee2d)
