### ISSUE TITLE
not a syntype

### ISSUE THREAD

**Issue by klausriede** [sfg-taxonpages/orthoptera#96]
https://orthoptera.speciesfile.org/otus/821996/overview

...and the paratype has an interesting Colombian? toponym

**Comment by typophyllum** [comment]
Stål 1878 mentions male and female, a measurement range, and two collections (Holm and Coll. Brunner), so there are at least two syntypes. The male syntype could be in Vienna. The female in the MfN labelled as paratype is either another syntype or no type at all. Since it belongs to this species the locality label is definitely wrong.

**Comment by klausriede** [comment]
so the Typus belongs to the rijksmuseum , and the "Paratypus" with the wrong locality label somehow ended up in Berlin (something to do with this Dämel? collector).

**Comment by typophyllum** [comment]
The status of the female specimen in Berlin is unclear. Apart from the female syntype in Stockholm there existed a male which could have been the one in Brunner's collection. According to his notes Carbonell did not find specimens of Agesander ruficornis in Vienna or Berlin.

**Comment by klausriede** [comment]
just found that Daemel sold insects...https://de.bionomia.net/Q5340390/specimens?action=collected&family=Convolvulaceae
